# Variables in Python

In [33]:
var1 = "Mohak Chugh"
var1

'Mohak Chugh'

In [34]:
var1 = 5.5
var1

5.5

In [35]:
var1 = 4 + 7j
type(var1)

complex

# Logical Operators

In [36]:
a = 10
b = 25

a < b

True

In [37]:
a != b

True

In [38]:
a == b

False

In [39]:
a & b

8

In [40]:
a = True
b = False
a | b

True

# Strings and Slicing in Python


In [41]:
name = "Mohak Chugh"
name[-5]

'C'

In [42]:
name[-5:]

'Chugh'

In [43]:
name[0:5]

'Mohak'

In [44]:
len(name)

11

In [45]:
name.upper()

'MOHAK CHUGH'

In [46]:
name.lower()

'mohak chugh'

In [47]:
name.title() 

'Mohak Chugh'

# Data Structures in Python

## Tuple

In [48]:
tup1 = (1, 3, 4, "Mohak")
tup1

(1, 3, 4, 'Mohak')

In [49]:
tup1[3]

'Mohak'

In [50]:
tup1[3] = "Chugh"

TypeError: 'tuple' object does not support item assignment

## List

In [9]:
list1 = [1, 2, 3, 4, "mohak", 3+4j, 5.3]
list1

[1, 2, 3, 4, 'mohak', (3+4j), 5.3]

In [10]:
list1.append("hi")
list1

[1, 2, 3, 4, 'mohak', (3+4j), 5.3, 'hi']

In [11]:
list1[4] = "Shakal"
list1 

[1, 2, 3, 4, 'Shakal', (3+4j), 5.3, 'hi']

In [12]:
list1.append(["name1", "name2", "name3"])
list1

[1, 2, 3, 4, 'Shakal', (3+4j), 5.3, 'hi', ['name1', 'name2', 'name3']]

In [13]:
list1.pop()
list1

[1, 2, 3, 4, 'Shakal', (3+4j), 5.3, 'hi']

## Dictionary

In [17]:
dict1 = {"mohak" : 1, "mohit": 2, "mansi" : 3}
dict1

{'mohak': 1, 'mohit': 2, 'mansi': 3}

In [18]:
dict1.keys()

dict_keys(['mohak', 'mohit', 'mansi'])

In [20]:
dict1.values()

dict_values([1, 2, 3])

In [22]:
dict1["mohit"] = 32
dict1["mohit"]

32

## Set - Which cant contain any duplicate

In [27]:
s1 = {1, 2, 3, 4}
s1

{1, 2, 3, 4}

In [28]:
s1.add("Mohak")
s1

{1, 2, 3, 4, 'Mohak'}

In [32]:
s1.remove("chutiya");
s1

{2, 3, 4, 'Mohak', 'hai', 'mohit'}

In [31]:
s1.update(["mohit", "hai"])
s1

{2, 3, 4, 'Mohak', 'chutiya', 'hai', 'mohit'}

# Conditionals

In [51]:
a = 10
b = 20

if (a > b):
    print("a is greater")
elif (a < b):
    print("a is smaller")
else:
    print("a is equal")

a is smaller


In [52]:
if 1 in tup1:
    print("Condition is True")

Condition is True


In [53]:
if dict1["mohak"]:
    print("Condition is true")

Condition is true


In [54]:
if 2 in list1:
    print("Condition is true")

Condition is true


In [55]:
if list1[2] == 2:
    print("Condition is True")
else:
    print("Condition is false")

Condition is false


# Loops and Iterators

In [57]:
i = 1
while (i < 10):
    print(i)
    i = i + 1;

1
2
3
4
5
6
7
8
9


In [58]:
for element in list1:
    print(element)

1
2
3
4
Shakal
(3+4j)
5.3
hi


In [59]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


# Functions and Classes

In [60]:
def function1():
    print("Mohak is the best")

function1()

Mohak is the best


In [61]:
class test:
        
    def func1(self):
        print("Func1 is called")


In [63]:
t1 = test()

In [65]:
t1.func1()

Func1 is called


In [67]:
# Inheritance
class test2(test):
    def func2(self):
        print("func2 is called")

t2 = test2()
t2.func2()

func2 is called


In [68]:
t2.func1()

Func1 is called


# Numpy - Understanding Basics

In [70]:
import numpy as np

In [71]:
n1 = np.array([1, 2, 3, 4, 4, 5, 6])
n1

array([1, 2, 3, 4, 4, 5, 6])

In [72]:
n2 = np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6]
])
n2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [76]:
n3 = np.zeros((4, 8))
n3

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [90]:
n4 = np.full((4, 8), 121)
n4

array([[121, 121, 121, 121, 121, 121, 121, 121],
       [121, 121, 121, 121, 121, 121, 121, 121],
       [121, 121, 121, 121, 121, 121, 121, 121],
       [121, 121, 121, 121, 121, 121, 121, 121]])

In [80]:
n5 = np.arange(10, 200, 30)
n5

array([ 10,  40,  70, 100, 130, 160, 190])

In [88]:
n6 = np.random.randint(0,10,6) # from, till, total nos
n6.shape = (2, 3)
n6

array([[4, 9, 5],
       [6, 7, 4]])

In [91]:
np.sum([n3,n4])


3872.0

In [92]:
np.sum([n3, n4], axis = 0)

array([[121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121.],
       [121., 121., 121., 121., 121., 121., 121., 121.]])

In [93]:
np.sum([n3, n4], axis = 1)

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [484., 484., 484., 484., 484., 484., 484., 484.]])

# Pandas - Basics

In [94]:
import pandas as pd

In [95]:
s1 = pd.Series([1, 2, 3, 4, 5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [99]:
s2 = pd.Series([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6]
])
s2

0    [1, 2, 3, 4, 5]
1    [2, 3, 4, 5, 6]
dtype: object

In [98]:
s3 = pd.Series(
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6]
)
s3

2    1
3    2
4    3
5    4
6    5
dtype: int64

In [100]:
s4 = pd.Series(dict1)
s4

mohak     1
mohit    32
mansi     3
dtype: int64

In [101]:
students = {
    "Student_Name": ["Mohak", "MOhit", "Mansi"],
    "Marks": [100, 0, 99]
}
students

{'Student_Name': ['Mohak', 'MOhit', 'Mansi'], 'Marks': [100, 0, 99]}

In [103]:
pd.DataFrame(students)

Student_Name  Marks
0        Mohak    100
1        MOhit      0
2        Mansi     99

In [109]:
iris = pd.read_csv('iris.csv')
iris.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [110]:
iris.tail(10)

sepallength  sepalwidth  petallength  petalwidth           class
140          6.7         3.1          5.6         2.4  Iris-virginica
141          6.9         3.1          5.1         2.3  Iris-virginica
142          5.8         2.7          5.1         1.9  Iris-virginica
143          6.8         3.2          5.9         2.3  Iris-virginica
144          6.7         3.3          5.7         2.5  Iris-virginica
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

In [111]:
iris.describe()

sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [116]:
sec1 = iris.iloc[0:6, 2:4] # Get x rows and y cols 
sec1

petallength  petalwidth
0          1.4         0.2
1          1.4         0.2
2          1.3         0.2
3          1.5         0.2
4          1.4         0.2
5          1.7         0.4

In [120]:
sec2 = iris.loc[0:6, ("petallength")]
sec2

0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
5    1.7
6    1.4
Name: petallength, dtype: float64

In [152]:
iris[(iris["sepalwidth"] > 3.9) & (iris["class"] == "Iris-setosa")]

sepallength  sepalwidth  petallength  petalwidth        class
14          5.8         4.0          1.2         0.2  Iris-setosa
15          5.7         4.4          1.5         0.4  Iris-setosa
32          5.2         4.1          1.5         0.1  Iris-setosa
33          5.5         4.2          1.4         0.2  Iris-setosa